### ISSUE TITLE
Is docopt-ng dead?

### ISSUE THREAD

**Issue by lhupfeldt** [jazzband/docopt-ng#12]
This question was previously asked about docopt, but now docopt-ng seems to have ended up in the same situation - unmerged/unanswered PRs and issues.
It would be really great to have a 'live' docopt for Python.

**Comment by pythonmobile** [comment]
Agreed.

**Comment by SeeSpotRun** [comment]
Whatever the next "live" fork is, the first step needs to be to set up a big enough and democratic enough maintenance team to make it sustainable.

**Comment by pythonmobile** [comment]
Perhaps anyone who is interested in maintaining/contributing, can chime in on this thread, and we can then fork and assemble a team?

**Comment by sesamemucho** [comment]
I'm in. I even have an issue, when the time comes.

**Comment by pythonmobile** [comment]
@sesamemucho I am not sure if we should write it from scratch or borrow the code? I think the first thing would be design/define the grammar for the docs.

**Comment by sesamemucho** [comment]
I was going to say "borrow the code", but then I looked at docopt.py in this repository. It's quite a complex piece for something without a clearly defined grammar. I'd like to help, but I have little experience in designing grammars.

**Comment by pythonmobile** [comment]
Lets see if we get some others interested, then we can meet online sometime and course a path forward. Initially we can keep the grammar simple.

**Comment by lhupfeldt** [comment]
Hi, sorry for being completely silent after starting this thread.

I'm not actually using docopt (in any form/package) at the moment. I gave it a short try some years ago, but gave up on it because of the difficulty of getting the spec correct, the really bad error messages presented to the users, and the belief of the author of the 'docopt' package that it was 'finished'. Så I have been using 'click' for some years, but that comes with a whole lot of different problems, making it really hard to create nice interfaces.

In my opinion the most critical issue with the docopt-ng implementation is the error messages presented to users. They are basically a dump of some internal state, which does not really help the user determine what is wrong with the input.
The docopt grammar is 'loosely' defined at docopt.org, I have not found a compilable grammar specification anywhere, all the implementations I have seen have hand coded the parser. @pythonmobile do you have experience in grammar specification? Starting from scratch is probably not a small job.

If you decide to put together a community driven project, I will be happy to participate, but cannot promise to put in a lot of effort. I already have a couple of projects requiring my attention.

I would really love to see a well functioning docopt though.

**Comment by pythonmobile** [comment]
@lhupfeldt I was thinking start with a simplified grammar, which takes a very few lines of code to parse and use. If we keep the grammar consistent and simple perhaps, instead of supporting all the bells and whistles..

**Comment by graingert** [comment]
perhaps it would be worth moving docopt and docopt-ng into https://github.com/jazzband/ to prevent this sort of lapse in maintainership in future

**Comment by itdaniher** [comment]
@graingert if you're volunteering or something - yes

**Comment by itdaniher** [comment]
Hi friends - sorry; I had to move ~7 times between June 2019 and June 2021. I now have a mortgage, and do not anticipate further offline spells. I have so much catchup here, and probably elsewhere! Thanks for your patience!

**Comment by itdaniher** [comment]
@lhupfeldt not dead, merely was in cryofreeze while I picked up the pieces of my life. Thanks for your patience!

**Comment by itdaniher** [comment]
@sesamemucho @graingert @pythonmobile let's talk more!

**Comment by itdaniher** [comment]
I'm itdaniher@gmail.com - if anyone in this thread wants to reach out with a vision for next steps, we can figure something out, and I'm happy to add you all as collabs to this project!

**Comment by graingert** [comment]
@itdaniher it's quite easy to register for a @jazzband membership and then transfer the repository in. Then the bots take over!

I can do this for you if you add me as a repository admin

**Comment by lhupfeldt** [comment]
Nice that you are back @itdaniher 
I see the project has already moved to jazzband.
@graingert I just took a look at jazzband. It seems there is only one person with the roadie role. I'm not sure what permissions different people get, but seems like the roadie is the super-admin?

**Comment by lhupfeldt** [comment]
There has been some suggestions about what should be done to move the project forward. Besides from handling the PR and the issues, I think the first focus should be on adding more tests of invalid input specs and on invalid arguments passed at runtime and the error messages presented.

**Comment by itdaniher** [comment]
@lhupfeldt @graingert moved to Jazzband! Thanks all!
