### ISSUE TITLE
Make PEP561 compatible (allow mypy to actually find type hints)

### ISSUE THREAD

**Issue by NickCrews** [jazzband/docopt-ng#18]
My project https://github.com/staticjinja/staticjinja uses mypy, but it can't actually use the type hints
defined here because we aren't following https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages

PR to follow

**Comment by NickCrews** [comment]
PR at https://github.com/jazzband/docopt-ng/pull/19

**Comment by alicederyn** [comment]
Is it possible for an end user to work around this issue, while the PR remains unmerged?

**Comment by NickCrews** [comment]
@alicederyn, not exactly sure what issue you mean, I'm assuming your mypy run is complaining that it can't find type hints for docopt? Is [this guide](https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker) helpful? Probably you will want to do one of the methods of suppressing the warning.

**Comment by alicederyn** [comment]
I was hoping there was a way to tell mypy how to use the type hints despite the misconfiguration fixed by your pr.

**Comment by NickCrews** [comment]
Ah, that is probably going to be trickier. Disclaimer, I'm moderately experienced, but by no means an expert in this packaging/environment stuff.

Is it possible for you to clone my fork that has that PR included, and install it as editable from that (ie `python3 -m pip install -e .`)?

Are you using some sort of package manager like poetry? In which case you could use a git requirement (https://python-poetry.org/docs/dependency-specification/#git-dependencies). 

Any other background or restrictions would be helpful.

**Comment by NickCrews** [comment]
Anything you need to move forward @alicederyn ?

**Comment by alicederyn** [comment]
I was going to come back to it, but I struggled to get docopt to support the configuration combinations I needed, and the error it gave when an extra argument was provided was not user-friendly, so I pulled it out and went with optparse instead :(

**Comment by NickCrews** [comment]
Closed via https://github.com/jazzband/docopt-ng/commit/de7c861dafb86418da423d4829f389a62c82151a
