### ISSUE TITLE
Add @NickCrews to test.pypi.org

### ISSUE THREAD

**Issue by NickCrews** [jazzband/docopt-ng#27]
@itdaniher not a big deal at all, but I would love it if I could test installs using the test mirror of PyPI. Could you add @NickCrews as a maintainer to https://test.pypi.org/project/docopt-ng/? Thanks!

**Comment by itdaniher** [comment]
![image](https://user-images.githubusercontent.com/22683/181130735-ceddbba0-7651-4e57-97b8-a844bc16c8a2.png)
Invite sent!
