### ISSUE TITLE
Is it possible to separate options in subsections?

### ISSUE THREAD

**Issue by Lord-Kamina** [jazzband/docopt-ng#43]
Many tools with a lot of options separate them in subsections in the help message; is it possible to do that in doctopt-ng?

**Comment by bittner** [comment]
Can you provide a good example of a tool that sports options with subsections? That would help to better understand this issue.

**Comment by Lord-Kamina** [comment]
Actually sorry, you can ignore this one. It turns out it just sort of works. I meant just having "headings" separating  groups of options. I thought it wouldn't work.
