### ISSUE TITLE
assert instr.opname.startswith("CALL_") throws on Python 3.11

### ISSUE THREAD

**Issue by lemenkov** [jazzband/docopt-ng#49]
Hello!
Similar to [this StackOverflow message](https://stackoverflow.com/questions/75505548/how-can-i-run-scripts-using-brownie) I've got the same error while trying to (indirectly) use docopt-ng with Python 3.11.

I've added `print(instr.opname)` right after the line 941 and the resulting list of  instructions indeed doesn't have anything stareted with CALL_ (see [file atached](https://github.com/jazzband/docopt-ng/files/11581694/list_ops.txt)). On the contrary here is a move shorter list of instructions when I run the same with Python 3.10:

```
LOAD_GLOBAL
LOAD_GLOBAL
LOAD_CONST
LOAD_CONST
CALL_FUNCTION_KW
```
If I remove the following block completely along with `output_value_assigned` variable then everything seems to work just fine with Python 3.11:

https://github.com/jazzband/docopt-ng/blob/130a5422feab5d4233a5a81102b02054634e36ce/docopt/__init__.py#L937-L950

**Comment by NickCrews** [comment]
Thanks for the report!

It was inevitable that something would break with how we are reaching into internals like this. The whole "magic" thing was a mistake of a feature I think, oh well.

I'll take a look and try to come up with some workaround.

**Comment by lemenkov** [comment]
So, apparently CALL_FUNCTION, CALL_FUNCTION_KW, CALL_METHOD, CALL_METHOD_KW [were removed](https://docs.python.org/3/whatsnew/3.11.html) from Python 3.11. See python/cpython#88691 for the details.

**Comment by lemenkov** [comment]
> Thanks for the report!
> 
> It was inevitable that something would break with how we are reaching into internals like this. The whole "magic" thing was a mistake of a feature I think, oh well.
> 
> I'll take a look and try to come up with some workaround.

Thanks! Looking forward to it!

**Comment by NickCrews** [comment]
OK, so brownie is using a vendored version of docopt, so if I fix the bug here then you won't see that change unless they pull that in. I still will look for the bug and probably fix it, but FYI you are going to have to go through more steps.
