### ISSUE TITLE
Support envvar token

### ISSUE THREAD

**Issue by alexiswl** [jazzband/docopt-ng#65]
Hello, 

Firstly thank you very much for giving this project a breath of life!

This [PR](https://github.com/docopt/docopt/pull/235) in the original docopt supported the envvar parameter.  It never made it in. 

Being able to know which environment variables have been specified in the documentation (like variables), would be very useful for the various projects I use docopt for. 

It would be great if this could be added into docopt-ng repo

**Comment by NickCrews** [comment]
Sorry, I'm gonna close this is as out of scope. Other non-python docopt implementations don't have it, this isn't part of the spec at docopt.org (which I don't have control over), and I think this can be implemented externally to docopt (please correct me if not), even if it is a little extra work. If I hear a whole lot of noise demanding this, we can revisit. Thank you!
